// Prometheus Design System — Figma bootstrap plugin (run2)
// Generated by design-system-extraction-code skill from tokens.json.
//
// Font rules:
//   - Figma expects "Semi Bold" with a space. "SemiBold" crashes.
//   - "Roboto Mono" / "DejaVu Sans Mono" are not bundled — use "Courier New".
//   - "Inter" is the ultimate safe fallback.

// ─── Token constants ────────────────────────────────────────────────────────

const BRAND_COLORS = {
  "brand/brand-blue": { r: 0.133, g: 0.545, b: 0.902 },
  "brand/nav-slate": { r: 0.255, g: 0.286, b: 0.318 },
};

const STATUS_COLORS = {
  ok: {
    light: { bg: { r: 0.827, g: 0.976, b: 0.847 }, text: { r: 0.169, g: 0.541, b: 0.243 }, border: "transparent" },
    dark:  { bg: { r: 0.169, g: 0.541, b: 0.243 }, text: { r: 0.827, g: 0.976, b: 0.847 }, border: "transparent" },
  },
  error: {
    light: { bg: { r: 1.000, g: 0.925, b: 0.925 }, text: { r: 0.788, g: 0.165, b: 0.165 }, border: "transparent" },
    dark:  { bg: { r: 0.788, g: 0.165, b: 0.165 }, text: { r: 1.000, g: 0.925, b: 0.925 }, border: "transparent" },
  },
  info: {
    light: { bg: { r: 0.133, g: 0.545, b: 0.902, a: 0.100 }, text: { r: 0.133, g: 0.545, b: 0.902 }, border: "transparent" },
    dark:  { bg: { r: 0.133, g: 0.545, b: 0.902, a: 0.150 }, text: { r: 0.455, g: 0.753, b: 0.988 }, border: "transparent" },
  },
};

const SURFACE_COLORS = {
  "surface/page-bg":       { light: { r: 1.000, g: 1.000, b: 1.000 }, dark: { r: 0.141, g: 0.141, b: 0.141 } },
  "surface/card-bg":       { light: { r: 1.000, g: 1.000, b: 1.000 }, dark: { r: 0.141, g: 0.141, b: 0.141 } },
  "surface/input-bg":      { light: { r: 1.000, g: 1.000, b: 1.000 }, dark: { r: 0.180, g: 0.180, b: 0.180 } },
  "surface/code-block-bg": { light: { r: 0, g: 0, b: 0, a: 0 },       dark: { r: 0.122, g: 0.122, b: 0.122 } },
  "surface/badge-bg":      { light: { r: 0.945, g: 0.953, b: 0.961 }, dark: { r: 0.204, g: 0.227, b: 0.251 } },
  "surface/header-bg":     { light: { r: 0.255, g: 0.286, b: 0.318 }, dark: { r: 0.255, g: 0.286, b: 0.318 } },
  "surface/icon-button-bg":{ light: { r: 0.525, g: 0.557, b: 0.588 }, dark: { r: 0.525, g: 0.557, b: 0.588 } },
};

const TEXT_COLORS = {
  "text/primary":   { light: { r: 0.000, g: 0.000, b: 0.000 }, dark: { r: 0.788, g: 0.788, b: 0.788 } },
  "text/secondary": { light: { r: 0.286, g: 0.314, b: 0.341 }, dark: { r: 0.678, g: 0.710, b: 0.741 } },
  "text/muted":     { light: { r: 0.525, g: 0.557, b: 0.588 }, dark: { r: 0.525, g: 0.557, b: 0.588 } },
  "text/inverted":  { light: { r: 1.000, g: 1.000, b: 1.000 }, dark: { r: 1.000, g: 1.000, b: 1.000 } },
  "text/link":      { light: { r: 0.133, g: 0.545, b: 0.902 }, dark: { r: 0.133, g: 0.545, b: 0.902 } },
};

const SPACING = {
  "spacing/xs": 4,
  "spacing/sm": 8,
  "spacing/md": 12,
  "spacing/lg": 16,
  "spacing/xl": 24,
  "spacing/2xl": 32,
};

const RADIUS = {
  "radius/none": 0,
  "radius/sm": 4,
  "radius/pill": 1000,
};

const TEXT_STYLES = [
  { name: "heading/page",           family: "Inter",        size: 24, weight: 700, lineHeight: 1.3  },
  { name: "heading/card-title",     family: "Inter",        size: 18, weight: 600, lineHeight: 1.4  },
  { name: "heading/section",        family: "Inter",        size: 16, weight: 600, lineHeight: 1.4  },
  { name: "body/default",           family: "Inter",        size: 14, weight: 400, lineHeight: 1.55 },
  { name: "body/strong",            family: "Inter",        size: 14, weight: 700, lineHeight: 1.55 },
  { name: "label/button-primary",   family: "Inter",        size: 14, weight: 600, lineHeight: 1.0  },
  { name: "label/button-secondary", family: "Inter",        size: 14, weight: 500, lineHeight: 1.0  },
  { name: "label/badge",            family: "Inter",        size: 11, weight: 700, lineHeight: 1.0  },
  { name: "code/block",             family: "Courier New",  size: 16, weight: 400, lineHeight: 1.5  },
  { name: "code/inline",            family: "Courier New",  size: 14, weight: 400, lineHeight: 1.4  },
];

const SHADOW_STYLES = [
  {
    name: "elevation/card",
    effects: [
      { type: "DROP_SHADOW", color: { r: 0, g: 0, b: 0, a: 0.05 }, offset: { x: 0, y: 1 }, radius: 3, spread: 0, visible: true, blendMode: "NORMAL" },
      { type: "DROP_SHADOW", color: { r: 0, g: 0, b: 0, a: 0.10 }, offset: { x: 0, y: 1 }, radius: 2, spread: 0, visible: true, blendMode: "NORMAL" },
    ],
  },
];

// ─── Variable collections ───────────────────────────────────────────────────

const TRANSPARENT_RGB = { r: 0, g: 0, b: 0, a: 0 };
const resolveColor = (v) => v === "transparent" ? TRANSPARENT_RGB : v;

async function createVariableCollections() {
  figma.notify("Creating variable collections…");
  console.log("[DS] Creating variable collections");

  const brandColl = figma.variables.createVariableCollection("Brand");
  const brandMode = brandColl.modes[0].modeId;
  for (const [name, rgb] of Object.entries(BRAND_COLORS)) {
    const v = figma.variables.createVariable(name, brandColl, "COLOR");
    v.setValueForMode(brandMode, rgb);
  }
  console.log(`[DS] Brand: ${Object.keys(BRAND_COLORS).length}`);

  const spacingColl = figma.variables.createVariableCollection("Spacing");
  const spacingMode = spacingColl.modes[0].modeId;
  for (const [name, value] of Object.entries(SPACING)) {
    const v = figma.variables.createVariable(name, spacingColl, "FLOAT");
    v.setValueForMode(spacingMode, value);
  }
  console.log(`[DS] Spacing: ${Object.keys(SPACING).length}`);

  const radiusColl = figma.variables.createVariableCollection("Radius");
  const radiusMode = radiusColl.modes[0].modeId;
  for (const [name, value] of Object.entries(RADIUS)) {
    const v = figma.variables.createVariable(name, radiusColl, "FLOAT");
    v.setValueForMode(radiusMode, value);
  }
  console.log(`[DS] Radius: ${Object.keys(RADIUS).length}`);

  const statusColl = figma.variables.createVariableCollection("Status Colors");
  const statusLight = statusColl.modes[0].modeId;
  statusColl.renameMode(statusLight, "Light");
  const statusDark = statusColl.addMode("Dark");
  for (const [status, modes] of Object.entries(STATUS_COLORS)) {
    for (const suffix of ["bg", "text", "border"]) {
      const v = figma.variables.createVariable(`status/${status}-${suffix}`, statusColl, "COLOR");
      v.setValueForMode(statusLight, resolveColor(modes.light[suffix]));
      v.setValueForMode(statusDark,  resolveColor(modes.dark[suffix]));
    }
  }
  console.log(`[DS] Status: ${Object.keys(STATUS_COLORS).length * 3}`);

  for (const [collName, tokenMap] of [["Surface", SURFACE_COLORS], ["Text", TEXT_COLORS]]) {
    const coll = figma.variables.createVariableCollection(collName);
    const lId = coll.modes[0].modeId;
    coll.renameMode(lId, "Light");
    const dId = coll.addMode("Dark");
    for (const [name, modes] of Object.entries(tokenMap)) {
      const v = figma.variables.createVariable(name, coll, "COLOR");
      v.setValueForMode(lId, resolveColor(modes.light));
      v.setValueForMode(dId, resolveColor(modes.dark));
    }
    console.log(`[DS] ${collName}: ${Object.keys(tokenMap).length}`);
  }
}

async function createTextStyles() {
  figma.notify("Creating text styles…");
  console.log(`[DS] Creating ${TEXT_STYLES.length} text styles`);

  for (const def of TEXT_STYLES) {
    const weightStyle =
      def.weight >= 700 ? "Bold" :
      def.weight >= 600 ? "Semi Bold" :
      def.weight >= 500 ? "Medium" :
      "Regular";

    let family = def.family;
    let style  = weightStyle;

    try {
      await figma.loadFontAsync({ family, style });
    } catch (_e1) {
      try {
        await figma.loadFontAsync({ family, style: "Regular" });
        style = "Regular";
      } catch (_e2) {
        try {
          await figma.loadFontAsync({ family: "Inter", style: weightStyle });
          family = "Inter";
        } catch (_e3) {
          await figma.loadFontAsync({ family: "Inter", style: "Regular" });
          family = "Inter";
          style  = "Regular";
        }
      }
    }

    const textStyle = figma.createTextStyle();
    textStyle.name     = def.name;
    textStyle.fontName = { family, style };
    textStyle.fontSize = def.size;
    textStyle.lineHeight = { value: def.lineHeight * 100, unit: "PERCENT" };
  }
}

async function createEffectStyles() {
  figma.notify("Creating elevation styles…");
  console.log(`[DS] Creating ${SHADOW_STYLES.length} effect styles`);
  for (const def of SHADOW_STYLES) {
    const style = figma.createEffectStyle();
    style.name    = def.name;
    style.effects = def.effects;
  }
}

async function main() {
  try {
    figma.notify("Prometheus DS bootstrap starting…", { timeout: 2000 });
    await createVariableCollections();
    await createTextStyles();
    await createEffectStyles();
    figma.notify("Bootstrap complete — 6 collections, 10 text styles, 1 shadow.", { timeout: 5000 });
  } catch (error) {
    const msg = error && error.message ? error.message : String(error);
    figma.notify("Error: " + msg, { error: true, timeout: 8000 });
    console.error("[DS] Plugin error:", error);
  } finally {
    figma.closePlugin();
  }
}

main();
